### ISSUE TITLE
QGIS2.ini vs QGIS2.org

### ISSUE THREAD

**Issue by gis-haderslev** [Frederikssund/Alternativ-QGIS-installation#2]
Vi har brugt din vejledning til installation af QGIS i Citrix. 
Prepare-fasen kører udmærket. Problemet opstår i RUN fasen : QGIS opretter og anvender en ny QGIS2.ini fil i samme mappe som QGIS2.org og bruger **.ini** filen i stedet for **.org** hvor vi har predefineret alle opsætnings parametre.

**Comment by Frederikssund** [comment]
Hej Nicolai - 

Dette er den korrekte måde for systemet. Hvis du kigger i "qgis-prepare.cmd" findes følgende linier (som udføres som en del af 1. gangs opstart af Qgis i "Run" fasen):

```
copy "%UN%\QGIS\QGIS2.ini" "%UN%\QGIS\QGIS2.org"
minised "s#%UO%#%UN%#g;s#%UO:/=\\\\%#%UN.... (forkortet)
```

Dvs. "QGIS2.org" er en kopi af "QGIS2.ini". Kopien bruges som indddata for kommandoen i næste linie. 
"minised" kommandoen laver en række search/replace for mappe og fil definitioner i QGIS2.org, således at oprindelige mappe definitioner - som var korrekte under "Prepare" fasen (og på den originale pc) - tilpasses til den nye placering på pc'en, hvor QGIS nu er installeret. Resultatet af kommandoen gemmes ved overskrivning af den originale QGIS2.ini.

Prøv at sammenligne QGIS2.org og QGIS2 .ini i en tekst editor efter du har opstartet QGIS 1. gang på en ny pc. Du vil se, at forskellene i filerne begrænser sig til en række mappe og fil definitioner i teksten. QGIS2.org indeholder teksten fra den originale QGIS2.ini, mens QGIS2.ini nu er tilpasset det nye miljø. 
(Det er QGIS2.ini, som QGIS rent faktisk bruger). QGIS2.org kan i princippet slettes, men er fornuftig at gemme, fordi man kan tjekke "før" og "efter" situationen ved 1. gangs opstart af QGIS på en ny pc. 

Der er altså ingen grund til direkte at redigere i QGIS2.ini - andet end hvad QGIS selv laver af ændringer ved installation af plugins og forskellige opsætninger under "prepare" fasen.

Hvis det er bydende nødvendigt, kan man under "prepare" fasen lave tilretninger i den QGIS2.**ini** fil, som befinder sig i mappe **"qgis_template\qgis"** under program mappen for QGIS. Det er nemlig den QGIS2.ini fil, som vil blive kopieret til brugernes senere hen.
